print("ingrese su primer nombre")
a = input()
print("ingrese su segundo nombre")
e = input()
print("ingrese su primer apellido")
w = input()
print("ingrese su segundo apellido")
s = input()
print("ingrese su edad")
d = input()
print("ingrese su año de nacimiento")
n = input()
print(f"nombre completo: {a} {e} {w} {s}")